---
- name: Launching Ec2 Instances in Aws
  hosts: localhost

  vars:
    instances: ["redis", "mysql", "rabbitmq", "catalog", "user", "cart", "shipping", "payment", "frontend"]
    operation: "create"
    domain_name: vinaysunke.online
    image_id: ami-0220d79f3f480ecf5

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      name: "roboshop-{{ item }}"
      image_id: "{{ image_id }}"
      security_groups:
      - "roboshop-{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
    when: operation == "create"
    ignore_errors: true

  # - name: print ec2_output
  #   debug:
  #     msg: "{{ ec2_output }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" #mongodb.daws90s.shop
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: operation == "create"

  - name: create r53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" #daws90s.shop
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend" 
    - operation == "create"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}.{{ domain_name }}" # mongodb.daws90s.shop
      ttl: 1
      type: A
    loop: "{{ instances  }}"  
    when: operation == "delete"

  - name: delete r53 record for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # daws90s.shop
      ttl: 1
      type: A
    loop: "{{ instances  }}"  
    when: 
    - operation == "delete"
    - item == "frontend"
  
  - name: delete ec2 instances
    amazon.aws.ec2_instance:
      state: absent
      name: "roboshop-{{ item }}"
      wait: false
    loop: "{{ instances  }}"  
    when: operation == "delete"